2024-09-01 15:34:12,879 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "/home/PycharmProjects/UrbanHomeworks/Module12/tests_12_4.py", line 56, in test_run
    runner_ = rt.Runner(183)
  File "/home/PycharmProjects/UrbanHomeworks/Module12/HumanMoveTest/rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-09-01 15:34:12,880 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "/home/PycharmProjects/UrbanHomeworks/Module12/tests_12_4.py", line 45, in test_walk
    runner_ = rt.Runner('Alex', -55)
  File "/home/PycharmProjects/UrbanHomeworks/Module12/HumanMoveTest/rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -55
